[features]
seeds = false
skip-lint = false

[programs.localnet]
scoring_demo_full = "7YPt7L7A7zZvBufGJ59pzWhcPgeVZgUVefi86nCs3jVa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juliotpaez/.config/solana/local.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
